apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: planningpoker-poker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: planningpoker-poker
    spec:
      containers:
        - name: planningpoker-poker
          image: nikneem/planningpoker-poker:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: secrets
              mountPath: /app/secrets
              readOnly: true
      volumes:
        - name: secrets
          secret:
            secretName: poker-appsettings
