apiVersion: extensions/v1
kind: Deployment
metadata:
  name: v
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: planningpoker-live
    spec:
      containers:
        - name: planningpoker-live
          image: nikneem/planningpoker-live:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: secrets
              mountPath: /app/secrets
              readOnly: true
      volumes:
        - name: secrets
          secret:
            secretName: live-appsettings
